### ISSUE TITLE
Không đủ labels

### ISSUE THREAD

**Issue by thangnch** [longphungtuan94/ALPR_System#1]
Hiện tại không để đủ label mà chỉ để từ 0-9 và vài ký tự nữa. Bạn có file label và file pb đủ ko ?

**Comment by longphungtuan94** [comment]
Mình không có, do hồi đấy data chủ yếu là crawl trên mạng + tự chụp ảnh ở ngoài nên chỉ kiếm các chữ cái phổ biến.
