### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.segmentation'

### ISSUE THREAD

**Issue by prasetyoandi** [longphungtuan94/ALPR_System#6]
i think everything is ok, module is also in the path. but this error still show up from 
`from utils.segmentation import segment_characters_from_plate`

**Comment by longphungtuan94** [comment]
Hello. Which script did you run? Did you run from the ALPR_Sytem directory?

**Comment by huygiangit96** [comment]
> i think everything is ok, module is also in the path. but this error still show up from
> `from utils.segmentation import segment_characters_from_plate`

You can change the name of the "utils" folder like "_utils" then also change in code. I think it was conflict with "utils" in tensorflow.

**Comment by prasetyoandi** [comment]
> > i think everything is ok, module is also in the path. but this error still show up from
> > `from utils.segmentation import segment_characters_from_plate`
> 
> You can change the name of the "utils" folder like "_utils" then also change in code. I think it was conflict with "utils" in tensorflow.

yea, thankyou i've missed it. but, mate. i have question, how to create custom char recognition model like `binary_128_0.50_ver3.pb`? @longphungtuan94 @huygiangit96

**Comment by huygiangit96** [comment]
> > > i think everything is ok, module is also in the path. but this error still show up from
> > > `from utils.segmentation import segment_characters_from_plate`
> > 
> > 
> > You can change the name of the "utils" folder like "_utils" then also change in code. I think it was conflict with "utils" in tensorflow.
> 
> yea, thankyou i've missed it. but, mate. i have question, how to create custom char recognition model like `binary_128_0.50_ver3.pb`? @longphungtuan94 @huygiangit96

You can follow this tutorial. It's quite simple 
https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#creating-label-map

**Comment by prasetyoandi** [comment]
> > > > i think everything is ok, module is also in the path. but this error still show up from
> > > > `from utils.segmentation import segment_characters_from_plate`
> > > 
> > > 
> > > You can change the name of the "utils" folder like "_utils" then also change in code. I think it was conflict with "utils" in tensorflow.
> > 
> > 
> > yea, thankyou i've missed it. but, mate. i have question, how to create custom char recognition model like `binary_128_0.50_ver3.pb`? @longphungtuan94 @huygiangit96
> 
> You can follow this tutorial. It's quite simple
> https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#creating-label-map

i think it's for object detection, not character recognition. maybe it's tensorflow attention_ocr, but it also can't read with my tf attention_ocr models.

**Comment by huygiangit96** [comment]
I guessed that. I've never used before so I don't know exactly. Sorry

**Comment by longphungtuan94** [comment]
> > > i think everything is ok, module is also in the path. but this error still show up from
> > > `from utils.segmentation import segment_characters_from_plate`
> > 
> > 
> > You can change the name of the "utils" folder like "_utils" then also change in code. I think it was conflict with "utils" in tensorflow.
> 
> yea, thankyou i've missed it. but, mate. i have question, how to create custom char recognition model like `binary_128_0.50_ver3.pb`? @longphungtuan94 @huygiangit96

Hi @prasetyoandi . I created the character recognition model based on this tutorial: https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#0
It's a CNN architecture called MobileNet, which is quite appropriate for real time recognition.

**Comment by prasetyoandi** [comment]
> > > > i think everything is ok, module is also in the path. but this error still show up from
> > > > `from utils.segmentation import segment_characters_from_plate`
> > > 
> > > 
> > > You can change the name of the "utils" folder like "_utils" then also change in code. I think it was conflict with "utils" in tensorflow.
> > 
> > 
> > yea, thankyou i've missed it. but, mate. i have question, how to create custom char recognition model like `binary_128_0.50_ver3.pb`? @longphungtuan94 @huygiangit96
> 
> Hi @prasetyoandi . I created the character recognition model based on this tutorial: https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#0
> It's a CNN architecture called MobileNet, which is quite appropriate for real time recognition.

is it means train every character(0-9 and A-Z)?, i don't get it

**Comment by longphungtuan94** [comment]
Yes, I trained an Image Classifier for 36 classes (10 classes (0-9) and 26 classes (A-Z)). Otherwise, you could increase accuracy by training 2 independent models, the first one only for number classification (0-9) and the other for character classification (A-Z)

**Comment by prasetyoandi** [comment]
yes, thankyou very much for sharing.

**Comment by charisma1919** [comment]
> 

this tutorial not found
can you suggest the other one?
i search on google and cannot find the same article
